### ISSUE TITLE
help , error occurs when run this example 

### ISSUE THREAD

**Issue by waynewgl** [ksachdeva/angular2-swiper-example#9]
http://localhost:3028/node_modules/swiper/dist/css/swiper.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:3028/node_modules/swiper/dist/js/swiper.js Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:24 Error: Error: XHR error (404 Not Found) loading http://localhost:3028/node_modules/swiper/dist/js/swiper.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3028/node_modules/zone.js/dist/zone.js:698:29)
	    at ZoneDelegate.invokeTask (http://localhost:3028/node_modules/zone.js/dist/zone.js:265:35)
	    at Zone.runTask (http://localhost:3028/node_modules/zone.js/dist/zone.js:154:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3028/node_modules/zone.js/dist/zone.js:335:33)
	Error loading http://localhost:3028/node_modules/swiper/dist/js/swiper.js as "swiper" from http://localhost:3028/node_modules/angular2-swiper/dist/ks-swiper.js
(anonymous) @ localhost/:24
swiper.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by waynewgl** [comment]
please have a look here, I followed the command introduced in the project github mainpage. and got the issue above..

**Comment by RicardoNeves** [comment]
I guess you're trying to import css and js by passing a path to your node_modules(which the browser can't access| which is correct). 

You need to have those files on a public folder or you can use the CDN provided on the README file:

```
<link href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.3.1/css/swiper.min.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.3.1/js/swiper.js"></script>
```
